name: Code Coverage

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest 

    # Step to checkout code from the repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to set up the Java Development Kit and specify the version
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11 

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Upload JaCoCo report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN=244745f1-f6fc-486d-a978-f652d51dd2aa }}
          file: ./target/jacoco-xml/jacoco.xml
          fail_ci: false
