name: JMeter Index
#Runs on pushes to dev and main
on:
  push:
    branches:
      - dev
      - main


jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
        #Downloads github repo onto the VM
      - name: Checkout code
        uses: actions/checkout@v3
        
         #Installs JMeter on the ubuntu VM         
      - name: Set up JMeter
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qy
          sudo apt-get install -qy jmeter
          
      - name: Run JMeter performance test
        # uses: QAInsights/PerfAction@f3959d0a69e7f23949add25d7e34a3ae167d6443
        uses: QAInsights/PerfAction@v3.1
        with:
        #Use testIndexPage jmx file from github repo
          test-plan-path: './testIndexPage.jmx'
          
      #Uploads a csv file in a zip folder once action is completed
      - name: Upload JMeter test results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-test-results
          path: jmeter-results.csv
