# Ivan Bibat
#GitHub Actions Workflow for Web Security Analysis

name: Site Security Analysis

# Event Trigger which pushes/pull requests to branches 'main' and 'dev' 
on:
  push:
    branches: 
      - dev
      - main
    
  pull_request:
    branches: 
      - dev
      - main


  
permissions: read


jobs:
  #Identifies the OS that the Workflow runs on.
  build:
    runs-on: ubuntu-latest
    
    steps:     
    - name: ZAP Baseline Scan
  
      uses: zaproxy/action-baseline@v0.10.0
      
      with:
        target: "https://WEBSITELINK.com/"
