name: Python Script Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Chrome browser version 114
      run: |
        yum install -y https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-$114-1.x86_64.rpm

    - name: Get latest ChromeDriver version
      id: get_version
      run: |
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        echo "Latest ChromeDriver version: $CHROMEDRIVER_VERSION"
        echo "::set-output name=chromedriver_version::$CHROMEDRIVER_VERSION"

    - name: Download ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=${{ steps.get_version.outputs.chromedriver_version }}
        wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have dependencies

    - name: Run Python script
      run: python test_python.py  